### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: strapd Bootloader
interface_branding_color: a7c080
interface_help_color: a7c080
interface_help_color_bright: a7c080
hash_mismatch_panic: no

term_background: 2d353b
backdrop: 2d353b

# Terminal colors (Everforest palette)
term_palette: 21272c;e67e80;a7c080;dbbc7f;7fbbb3;d699b6;83c092;d3c6aa
term_palette_bright: 475258;e67e80;a7c080;dbbc7f;7fbbb3;d699b6;83c092;d3c6aa

# Text colors
term_foreground: d3c6aa
term_foreground_bright: d3c6aa
term_background_bright: 343f44
