#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

TEST_HOME=$(mktemp -d)
WORK=$(mktemp -d)
trap 'rm -rf "$TEST_HOME" "$WORK"' EXIT

# The refresh command asks strapd-keybindings-generate which backends exist, by
# name, the way it will once bin/ is symlinked into /usr/bin.
export PATH="$ROOT/bin:$PATH"
export STRAPD_PATH="$ROOT"
export HOME="$TEST_HOME"

out_dir="$TEST_HOME/.local/state/strapd/keyboard"

# A box with no vconsole.conf at all, which is what a container looks like.
export STRAPD_VCONSOLE_CONF="$WORK/absent.conf"

strapd-refresh-keyboard-layout || fail "refresh succeeds with no vconsole.conf"
pass "refresh succeeds with no vconsole.conf"

grep -q '^            layout "us"$' "$out_dir/niri.kdl" || fail "no vconsole.conf falls back to us" "$(cat "$out_dir/niri.kdl")"
pass "no vconsole.conf falls back to us"

# Nothing declared a variant, so nothing should claim one: an empty variant line
# is not the same as no variant line to xkb.
grep -q 'variant' "$out_dir/niri.kdl" && fail "an absent variant is left out entirely" "$(cat "$out_dir/niri.kdl")"
pass "an absent variant is left out entirely"

for file in niri.kdl sway.conf mango.conf; do
  grep -q 'compose:caps,shift:both_capslock_cancel' "$out_dir/$file" ||
    fail "$file carries strapd's xkb options" "$(cat "$out_dir/$file")"
  pass "$file carries strapd's xkb options"
done

[[ $(head -n 1 "$out_dir/niri.kdl") == "// Generated by strapd-refresh-keyboard-layout"* ]] ||
  fail "niri.kdl opens with a KDL comment header" "$(head -n 1 "$out_dir/niri.kdl")"
pass "niri.kdl opens with a KDL comment header"

for file in sway.conf mango.conf; do
  [[ $(head -n 1 "$out_dir/$file") == "# Generated by strapd-refresh-keyboard-layout"* ]] ||
    fail "$file opens with a # comment header" "$(head -n 1 "$out_dir/$file")"
  pass "$file opens with a # comment header"
done

# The layout the installer actually wrote, in each compositor's own spelling.
cat >"$WORK/fr.conf" <<'CONF'
KEYMAP=fr
XKBLAYOUT=fr
XKBVARIANT=azerty
CONF
export STRAPD_VCONSOLE_CONF="$WORK/fr.conf"

strapd-refresh-keyboard-layout || fail "refresh succeeds against a real vconsole.conf"
pass "refresh succeeds against a real vconsole.conf"

grep -q '^            layout "fr"$' "$out_dir/niri.kdl" || fail "niri.kdl takes the layout from vconsole.conf" "$(cat "$out_dir/niri.kdl")"
pass "niri.kdl takes the layout from vconsole.conf"

grep -q '^            variant "azerty"$' "$out_dir/niri.kdl" || fail "niri.kdl takes the variant from vconsole.conf" "$(cat "$out_dir/niri.kdl")"
pass "niri.kdl takes the variant from vconsole.conf"

grep -q '^    xkb_layout "fr"$' "$out_dir/sway.conf" || fail "sway.conf takes the layout from vconsole.conf" "$(cat "$out_dir/sway.conf")"
pass "sway.conf takes the layout from vconsole.conf"

grep -q '^xkb_rules_layout=fr$' "$out_dir/mango.conf" || fail "mango.conf takes the layout from vconsole.conf" "$(cat "$out_dir/mango.conf")"
pass "mango.conf takes the layout from vconsole.conf"

grep -q '^xkb_rules_variant=azerty$' "$out_dir/mango.conf" || fail "mango.conf takes the variant from vconsole.conf" "$(cat "$out_dir/mango.conf")"
pass "mango.conf takes the variant from vconsole.conf"

# A layout that cannot type Latin letters decides whether the desktop is usable
# at all: every bind strapd ships is a Latin keysym, and a compositor resolves
# binds against the first layout in the list.
cat >"$WORK/ru.conf" <<'CONF'
KEYMAP=ru
XKBLAYOUT=ru
CONF
export STRAPD_VCONSOLE_CONF="$WORK/ru.conf"

strapd-refresh-keyboard-layout || fail "refresh succeeds against a non-Latin layout"
pass "refresh succeeds against a non-Latin layout"

grep -q '^            layout "us,ru"$' "$out_dir/niri.kdl" || fail "a non-Latin layout gets us in front of it" "$(cat "$out_dir/niri.kdl")"
pass "a non-Latin layout gets us in front of it"

grep -q 'grp:alts_toggle' "$out_dir/niri.kdl" || fail "a non-Latin layout stays reachable with both Alts" "$(cat "$out_dir/niri.kdl")"
pass "a non-Latin layout stays reachable with both Alts"

# The variant list is positional, so the entry pushed in front of it has to be
# there too or every layout's variant is off by one.
grep -q '^            variant ","$' "$out_dir/niri.kdl" || fail "the variant list keeps its place against the layout list" "$(cat "$out_dir/niri.kdl")"
pass "the variant list keeps its place against the layout list"

leftovers=$(find "$out_dir" -maxdepth 1 -name '.*.new' -print)
[[ -z $leftovers ]] || fail "refresh leaves no staging files behind" "$leftovers"
pass "refresh leaves no staging files behind"

# A backend that gets keybindings and no keyboard layout comes up us and
# unusable on a non-Latin install, so a fourth added to the generator and not
# here has to be loud.
mkdir -p "$WORK/fake-bin"
cat >"$WORK/fake-bin/strapd-keybindings-generate" <<'FAKE'
#!/bin/bash
printf '%s\n' niri sway mango river
FAKE
chmod +x "$WORK/fake-bin/strapd-keybindings-generate"

PATH="$WORK/fake-bin:$PATH" strapd-refresh-keyboard-layout 2>/dev/null &&
  fail "a backend the generator knows and this script does not is an error"
pass "a backend the generator knows and this script does not is an error"
