#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

require_command yq
require_command jq

TEST_HOME=$(mktemp -d)
trap 'rm -rf "$TEST_HOME"' EXIT

FIXTURES="$ROOT/test/shell.d/fixtures/keybindings"

# strapd-refresh-keybindings calls the generator by name, the way it will once
# bin/ is symlinked into /usr/bin; STRAPD_PATH points that generator at this
# checkout's keybindings/ instead of the installed tree.
export PATH="$ROOT/bin:$PATH"
export STRAPD_PATH="$ROOT"
export HOME="$TEST_HOME"

out_dir="$TEST_HOME/.local/state/strapd/keybindings"

strapd-refresh-keybindings || fail "refresh succeeds against the shipped table"
pass "refresh succeeds against the shipped table"

for file in niri.kdl sway.conf mango.conf; do
  [[ -f $out_dir/$file ]] || fail "refresh writes $file" "not found in $out_dir"
  pass "refresh writes $file"
done

# Each file is the backend's real syntax, not another backend's -- repeated from
# the generator's own test because this script is what decides which rendering
# lands in which file.
grep -q '^binds {' "$out_dir/niri.kdl" || fail "niri.kdl holds a niri binds block" "$(cat "$out_dir/niri.kdl")"
pass "niri.kdl holds a niri binds block"

grep -q '^bindsym ' "$out_dir/sway.conf" || fail "sway.conf holds sway bindsym lines" "$(cat "$out_dir/sway.conf")"
pass "sway.conf holds sway bindsym lines"

grep -q '^bind=' "$out_dir/mango.conf" || fail "mango.conf holds mango bind= lines" "$(cat "$out_dir/mango.conf")"
pass "mango.conf holds mango bind= lines"

# The header has to be a comment in the file's own language, or the first thing
# the compositor reads is a syntax error.
[[ $(head -n 1 "$out_dir/niri.kdl") == "// Generated by strapd-refresh-keybindings"* ]] ||
  fail "niri.kdl opens with a KDL comment header" "$(head -n 1 "$out_dir/niri.kdl")"
pass "niri.kdl opens with a KDL comment header"

for file in sway.conf mango.conf; do
  [[ $(head -n 1 "$out_dir/$file") == "# Generated by strapd-refresh-keybindings"* ]] ||
    fail "$file opens with a # comment header" "$(head -n 1 "$out_dir/$file")"
  pass "$file opens with a # comment header"
done

# A table the user has taken over wins over the shipped one. minimal.toml has
# window.close and no window.fullscreen, so the two renderings are
# distinguishable by content, not just by the path in the header.
grep -q 'fullscreen' "$out_dir/sway.conf" || fail "the shipped table renders window.fullscreen" "$(cat "$out_dir/sway.conf")"
pass "the shipped table renders window.fullscreen"

mkdir -p "$TEST_HOME/.config/strapd"
cp "$FIXTURES/minimal.toml" "$TEST_HOME/.config/strapd/keybindings.toml"

strapd-refresh-keybindings || fail "refresh succeeds against a user table"
pass "refresh succeeds against a user table"

grep -q 'fullscreen' "$out_dir/sway.conf" && fail "the user table replaces the shipped one" "$(cat "$out_dir/sway.conf")"
pass "the user table replaces the shipped one"

grep -q '^bindsym [$]mod+w kill$' "$out_dir/sway.conf" || fail "the user table's own bindings render" "$(cat "$out_dir/sway.conf")"
pass "the user table's own bindings render"

grep -q "$TEST_HOME/.config/strapd/keybindings.toml" "$out_dir/sway.conf" ||
  fail "the header names the table the file came from" "$(head -n 3 "$out_dir/sway.conf")"
pass "the header names the table the file came from"

# The compositor reading these is running while this command runs, so a table
# that fails validation has to leave the last good files exactly as they were.
before=$(cat "$out_dir"/niri.kdl "$out_dir"/sway.conf "$out_dir"/mango.conf)

cp "$FIXTURES/invalid-unsupported-no-reason.toml" "$TEST_HOME/.config/strapd/keybindings.toml"

strapd-refresh-keybindings 2>/dev/null && fail "refresh fails on a table that does not validate"
pass "refresh fails on a table that does not validate"

[[ $(cat "$out_dir"/niri.kdl "$out_dir"/sway.conf "$out_dir"/mango.conf) == "$before" ]] ||
  fail "a failed refresh leaves the last good configs in place"
pass "a failed refresh leaves the last good configs in place"

# Staging is a dotfile inside the output directory; a failed run that left it
# behind would put a half-written config where the compositor globs for one.
leftovers=$(find "$out_dir" -maxdepth 1 -name '.staging.*' -print)
[[ -z $leftovers ]] || fail "a failed refresh cleans up its staging directory" "$leftovers"
pass "a failed refresh cleans up its staging directory"
