# Your look and feel. strapd's are in
# /usr/share/strapd/default/sway/looknfeel.conf.
#
# gaps inner 2
# gaps outer 0
# default_border pixel 4
#
# Bring back titlebars, which strapd turns off:
#
# default_border normal 2
