# homeManagerModules.strapd, the user half of the NixOS layer.
#
# On Arch, place-tree.sh seeds /etc/skel and useradd -m copies it into a new
# home, exactly once. This module keeps those semantics but drops the
# copy-once trap: every home-manager generation seeds whatever is missing and
# never touches a file that exists. The seeded files are the documented user
# edit points (config/niri/bindings.kdl and friends carry "edit me" comments),
# so read-only store symlinks would break the product's own customization
# story, declarative seeding, imperative ownership afterward.
#
# Safe across rebuilds because the seeded files reference the tree as
# /etc/strapd (rewritten at package build time), never as a store path.
#
# What is deliberately left alone, because it is state rather than config:
#   ~/.local/state/strapd/**   keybindings, keyboard, current/theme;
#                              regenerated by strapd-session at every login
#   ~/.config/strapd/**        user overrides, owned by the user
self: { config, lib, pkgs, ... }:

let
  cfg = config.strapd;
  system = pkgs.stdenv.hostPlatform.system;
in
{
  options.strapd = {
    enable = lib.mkEnableOption "strapd's user configuration seeding";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${system}.strapd;
      defaultText = lib.literalExpression "strapd.packages.\${system}.strapd";
      description = ''
        The strapd tree to seed from. When this module runs inside the NixOS
        configuration that also sets strapd.package, point it at the same
        package.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.activation.strapdSeedConfigs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      # Mirrors place-tree.sh's skel block: config/ -> ~/.config,
      # default/bashrc -> ~/.bashrc. install(1) rather than cp: the source is
      # the read-only store, and the copy must arrive writable.
      strapdSeed() {
        local source="$1" dest="$2"
        [ -e "$dest" ] && return 0
        run install -D -m 0644 "$source" "$dest"
      }

      while IFS= read -r -d "" file; do
        strapdSeed "$file" "$HOME/.config/''${file#${cfg.package}/share/strapd/config/}"
      done < <(${pkgs.findutils}/bin/find ${cfg.package}/share/strapd/config -type f -print0)

      strapdSeed ${cfg.package}/share/strapd/default/bashrc "$HOME/.bashrc"
    '';

    # What install/user/theme.sh did on Arch, done declaratively here because
    # the NixOS layer drops the install/-based provisioning that ran it.
    # strapd-theme-set expands the theme's templates into
    # ~/.local/state/strapd/current/theme, the palette the terminal, btop,
    # editor and the rest read through, which the seeded config/ tree
    # references but cannot itself produce. Guarded on theme.name so a theme
    # the user later chooses is never reverted on a rebuild; STRAPD_THEME_HEADLESS
    # because activation runs with no session to notify. strapd-theme-set
    # resolves the tree through /etc/strapd (env-bootstrap's rewritten default),
    # placed by the NixOS module before user activation runs.
    home.activation.strapdSeedTheme = lib.hm.dag.entryAfter [ "strapdSeedConfigs" ] ''
      export PATH="${cfg.package}/bin:${lib.makeBinPath cfg.package.passthru.runtimeDeps}:$PATH"
      if [ ! -s "$HOME/.local/state/strapd/current/theme.name" ]; then
        run env STRAPD_THEME_HEADLESS=1 strapd-theme-set Everforest
      fi
      # theme.sh's tail: btop reads its palette through this stable symlink.
      run mkdir -p "$HOME/.config/btop/themes"
      run ln -snf "$HOME/.local/state/strapd/current/theme/btop.theme" \
        "$HOME/.config/btop/themes/current.theme"
    '';
  };
}
